tp1: main.cpp func.cpp
	g++ -o tp1 main.cpp func.cpp

run: main.cpp func.cpp
	g++ -o tp1 main.cpp func.cpp
	clear
	./tp1 ../tst/teste.a

val:main.cpp func.cpp
	g++ -o tp1 main.cpp func.cpp
	clear
	valgrind --leak-check=full --track-origins=yes ./tp1 ../tst/teste.a